(() => {
  const PP=window.PartyPlay,$=(s)=>document.querySelector(s);const params=new URLSearchParams(location.search),code=(params.get('room')||'').toUpperCase();if(!code){location.replace('join.html');return}$('#displayCode').textContent=code;$('#displayRoom').textContent=`ROOM ${code}`;const client=new PartyPlayLiveClient();let current=null;
  const show=(id,yes=true)=>$(id)?.classList.toggle('hidden',!yes);
  const meta={quiz:'🧠 QUIZ',learn:'🎓 LEARN',puzzle:'🧩 PUZZLE',task:'🏆 TASK',social:'🗳 SOCIAL',visual:'📸 VISUAL',music:'🎵 MUSIC'};
  function scores(list=[]){$('#displayScores').innerHTML=[...list].sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,8).map((s,i)=>`<div class="display-score">${i+1}. ${PP.escapeHTML(s.name)} <b>${s.score||0}</b></div>`).join('')}
  client.on('joined',()=>{});client.on('round-start',msg=>{current=msg.round;show('#displayWaiting',false);show('#displayWinner',false);show('#displayRound',true);$('#displayRoundNum').textContent=`ROUND ${msg.roundIndex+1} / ${msg.totalRounds}`;$('#displayTurn').textContent=msg.turn||'Everyone plays';$('#displayTimer').textContent=msg.duration||'—';$('#displayType').innerHTML=`<span class="round-engine">${meta[current.engine]||'🎲 ROUND'}</span><span class="difficulty-pill">${PP.escapeHTML(current.category||'Mixed')}</span>`;$('#displayPrompt').textContent=current.prompt;show('#displayAnswer',false);const media=$('#displayMedia');media.innerHTML='';show('#displayMedia',true);if(current.engine==='visual'&&current.visual?.image){const img=document.createElement('img');img.src=current.visual.image;img.alt=current.visual.alt||'Visual clue';img.onerror=()=>{media.innerHTML='<div class="visual-placeholder">🗺️</div>'};media.appendChild(img)}else show('#displayMedia',false);scores(msg.scores||[])});
  client.on('timer',msg=>{$('#displayTimer').textContent=String(Math.max(0,msg.timeLeft)).padStart(2,'0')});client.on('round-result',msg=>{$('#displayAnswer').textContent=msg.answer||'Host judged';show('#displayAnswer',true);scores(msg.scores||[])});client.on('game-finished',msg=>{show('#displayRound',false);show('#displayWaiting',false);show('#displayWinner',true);$('#displayWinnerName').textContent=msg.winner||'Winner';$('#displayPrize').textContent=msg.prize?`Winner award: ${msg.prize}`:'';show('#displayPrize',!!msg.prize);$('#displayFinalScores').innerHTML=(msg.scores||[]).map((s,i)=>`<div class="display-score">${i+1}. ${PP.escapeHTML(s.name)} <b>${s.score||0}</b></div>`).join('');const awards=Array.isArray(msg.awards)?msg.awards:[];$('#displayAwards').innerHTML=awards.map(a=>`<div class="recognition-row"><span>${a[0]||'🏅'}</span><div><b>${PP.escapeHTML(a[1]||'Award')}</b><small>${PP.escapeHTML(a[2]||'')} · ${PP.escapeHTML(a[3]||'')}</small></div></div>`).join('');show('#displayAwards',!!awards.length)});
  client.connect().then(()=>client.send('join-room',{code,name:'Big Screen',role:'display'})).catch(()=>{$('#displayWaiting h1').textContent='Live server unavailable';$('#displayWaiting p').textContent='Start the included PartyPlay realtime server, then reload this display.'});
})();
