(() => {
  const PP=window.PartyPlay,$=(s)=>document.querySelector(s);
  const params=new URLSearchParams(location.search);if(params.get('room'))$('#roomCode').value=params.get('room').toUpperCase();
  let client=null,roomInfo=null,joined=false,currentRound=null,roundStartedAt=0,orderState=[],submitted=false,selectedWager=0,participant={id:'',teamId:'',name:''};
  const show=(id,yes=true)=>$(id)?.classList.toggle('hidden',!yes);
  function connect(){if(client?.connected)return Promise.resolve(client);client=new PartyPlayLiveClient();wire();return client.connect()}
  function wire(){
    client.on('room-info',msg=>{roomInfo=msg.session||{};const teams=roomInfo.teams||[];if(roomInfo.playStyle==='teams'&&teams.length){$('#teamSelect').innerHTML=teams.map(t=>`<option value="${t.id}">${PP.escapeHTML(t.name)}</option>`).join('');show('#teamPicker',true);const btn=$('#joinForm button[type="submit"]');btn.textContent='Join selected team →';btn.dataset.ready='1'}else joinNow()});
    client.on('joined',msg=>{joined=true;participant={id:msg.participantId,teamId:msg.teamId||'',name:msg.name,role:msg.role||'player'};$('#controllerRoom').textContent=`ROOM ${msg.code}`;show('#joinFormCard',false);show('#playerController',true);$('#connectionState').textContent='Connected';history.replaceState({},'',`join.html?room=${encodeURIComponent(msg.code)}`)});
    client.on('room-error',msg=>{$('#joinError').textContent=msg.message||'Could not join this room.'});
    client.on('round-start',msg=>renderRound(msg));
    client.on('answer-locked',msg=>lockState(msg));
    client.on('round-result',msg=>showResult(msg));
    client.on('timer',msg=>{const meta=$('#controllerMeta');if(meta&&currentRound)meta.dataset.timeLeft=msg.timeLeft});
    client.on('game-finished',msg=>{show('#controllerWaiting',false);show('#controllerRound',false);show('#controllerResult',true);$('#resultMark').textContent='🏆';$('#resultTitle').textContent=`${msg.winner||'Winner'} wins!`;$('#resultDetail').textContent=msg.prize?`Winner award: ${msg.prize}`:'Game complete. Thanks for playing.'});
    client.on('disconnected',()=>{$('#connectionState').textContent='Reconnecting needed';});
  }
  function joinNow(){const code=$('#roomCode').value.trim().toUpperCase(),name=$('#playerName').value.trim();client.send('join-room',{code,name,role:$('#joinRole').value,teamId:$('#teamPicker').classList.contains('hidden')?'':$('#teamSelect').value,resumeToken:client.resumeToken})}
  $('#joinForm').addEventListener('submit',async e=>{e.preventDefault();$('#joinError').textContent='';const code=$('#roomCode').value.trim().toUpperCase(),name=$('#playerName').value.trim();if(code.length<4||!name){$('#joinError').textContent='Enter the game code and your name.';return}try{await connect();if($('#joinForm button[type="submit"]').dataset.ready==='1')joinNow();else client.send('room-info-request',{code})}catch(err){$('#joinError').textContent='PartyPlay Live server is unavailable. Ask the host to start the included realtime server.'}});
  function roundMeta(round){const names={quiz:'🧠 QUIZ',learn:'🎓 LEARN',puzzle:'🧩 PUZZLE',task:'🏆 TASK',social:'🗳 SOCIAL',visual:'📸 VISUAL',music:'🎵 MUSIC'};return names[round.engine]||'🎲 ROUND'}
  function renderWagerChoices(options){const box=$('#controllerWager'),root=$('#controllerWagerChoices');root.innerHTML='';if(participant.role!=='player'||!Array.isArray(options)||options.length<2){show('#controllerWager',false);return}show('#controllerWager',true);options.forEach(pct=>{const b=document.createElement('button');b.type='button';b.className='wager-choice'+(Number(pct)===0?' selected':'');b.textContent=Number(pct)===0?'No wager':Number(pct)===1?'All-in +100%':`Risk ${Math.round(Number(pct)*100)}%`;b.onclick=()=>{selectedWager=Number(pct)||0;root.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')};root.appendChild(b)})}
  function renderRound(msg){
    currentRound=msg.round;roundStartedAt=Date.now();submitted=false;selectedWager=0;orderState=[];show('#controllerWaiting',false);show('#controllerResult',false);show('#controllerRound',true);show('#controllerLocked',false);show('#controllerInteraction',true);$('#controllerMeta').innerHTML=`<span class="round-engine">${roundMeta(currentRound)}</span><span class="difficulty-pill">${PP.escapeHTML(currentRound.category||'Mixed')}</span>`;$('#controllerPrompt').textContent=currentRound.prompt;const root=$('#controllerInteraction');root.innerHTML='';renderWagerChoices(msg.wagerOptions||[]);
    if(participant.role==='audience'||participant.role==='display'){root.innerHTML='<div class="task-box"><p>Audience mode: follow the main screen. You are not included in competitive scoring.</p></div>';return}
    if((currentRound.engine==='quiz'||currentRound.engine==='learn')&&currentRound.options?.length){const grid=document.createElement('div');grid.className='option-grid';currentRound.options.forEach(o=>{const b=document.createElement('button');b.type='button';b.className='option-btn';b.textContent=o;b.addEventListener('click',()=>submit(o));grid.appendChild(b)});root.appendChild(grid);return}
    if(currentRound.engine==='puzzle'&&currentRound.puzzle?.kind==='order'){orderState=[...(currentRound.puzzle.items||[])];const list=document.createElement('div');list.className='puzzle-order';const draw=()=>{list.innerHTML='';orderState.forEach((item,i)=>{const row=document.createElement('div');row.className='order-row';row.innerHTML=`<span>${i+1}</span><b>${PP.escapeHTML(item)}</b><button type="button">↑</button><button type="button">↓</button>`;const [up,down]=row.querySelectorAll('button');up.disabled=i===0;down.disabled=i===orderState.length-1;up.onclick=()=>{if(i>0){[orderState[i-1],orderState[i]]=[orderState[i],orderState[i-1]];draw()}};down.onclick=()=>{if(i<orderState.length-1){[orderState[i+1],orderState[i]]=[orderState[i],orderState[i+1]];draw()}};list.appendChild(row)});const send=document.createElement('button');send.type='button';send.className='btn primary full';send.textContent='Submit order';send.onclick=()=>submit(orderState);list.appendChild(send)};draw();root.appendChild(list);return}
    if(currentRound.engine==='task'){
      const box=document.createElement('div');box.className='task-box';box.innerHTML='<p>Complete the challenge. The host will judge the result.</p>';
      if(currentRound.task?.proof==='photo'){const label=document.createElement('label');label.className='btn primary full';label.innerHTML='📷 Take proof photo <input type="file" accept="image/*" capture="environment" hidden>';const input=label.querySelector('input');input.addEventListener('change',async()=>{if(!input.files?.[0])return;const dataUrl=await compress(input.files[0]);const img=document.createElement('img');img.src=dataUrl;img.className='proof-preview';box.appendChild(img);client.send('photo-submit',{code:$('#roomCode').value.trim().toUpperCase(),roundId:currentRound.id,dataUrl});label.textContent='Photo sent ✓'});box.appendChild(label)}root.appendChild(box);return
    }
    if(currentRound.engine==='social'||currentRound.engine==='music'){root.innerHTML='<div class="task-box"><p>This round is hosted on the main screen. Follow the host instructions and submit when asked.</p></div>';return}
    const wrap=document.createElement('div');wrap.className='typed-answer';wrap.innerHTML='<input placeholder="Type your answer…" autocomplete="off"><button class="btn primary" type="button">Submit</button>';wrap.querySelector('button').onclick=()=>submit(wrap.querySelector('input').value);wrap.querySelector('input').addEventListener('keydown',e=>{if(e.key==='Enter')submit(wrap.querySelector('input').value)});root.appendChild(wrap)
  }
  function submit(answer){if(submitted)return;submitted=true;client.send('answer',{code:$('#roomCode').value.trim().toUpperCase(),answer,wagerPct:selectedWager,clientElapsedMs:Date.now()-roundStartedAt})}
  function lockState(msg){show('#controllerInteraction',false);show('#controllerWager',false);show('#controllerLocked',true);$('#lockedTime').textContent=`Locked in ${(Math.max(0,Number(msg.serverElapsedMs ?? (msg.receivedAt-roundStartedAt)))/1000).toFixed(2)}s`}
  function showResult(msg){const mine=(msg.results||[]).find(r=>r.participantId===client.participantId);show('#controllerRound',false);show('#controllerResult',true);if(mine){$('#resultMark').textContent=mine.correct?'✓':'✕';$('#resultTitle').textContent=mine.correct?'Correct!':'Not this time';$('#resultDetail').textContent=mine.correct?`+${mine.awarded||0} points${mine.wagerPct?` · ${Math.round(mine.wagerPct*100)}% wager`:''} · Answer: ${msg.answer}`:mine.awarded<0?`${mine.awarded} risk points · Answer: ${msg.answer}`:`Answer: ${msg.answer}`}else{$('#resultMark').textContent='•';$('#resultTitle').textContent='Round complete';$('#resultDetail').textContent=`Answer: ${msg.answer}`}
    const score=(msg.scores||[]).find(s=>s.id===(roomInfo?.playStyle==='teams'?participant.teamId:client.participantId));if(score)$('#controllerScore').textContent=score.score||0
  }
  async function compress(file){return new Promise((resolve,reject)=>{const img=new Image(),fr=new FileReader();fr.onload=()=>img.src=fr.result;fr.onerror=reject;img.onload=()=>{const max=800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.68))};fr.readAsDataURL(file)})}
})();
