(() => {
  const PP=window.PartyPlay,$=(s)=>document.querySelector(s),$$=(s)=>[...document.querySelectorAll(s)];
  const params=new URLSearchParams(location.search);const requestedMode=params.get('mode')||'local';
  let session=PP.load(PP.STORAGE.session,null);if(!session?.deck?.length){location.replace('setup.html?mode=party');return}
  session.live=requestedMode==='live';
  let roundIndex=Math.max(0,Math.min(session.roundIndex||0,session.deck.length-1));
  let competitorIndex=session.competitorIndex||0;let currentRound=null;let revealed=false;let roundStartedAt=0;let timerId=null;let timeLeft=0;let liveClient=null;let liveRoom='';let liveParticipants=[];let liveResponses=[];let evidence=[];let localSelection=null;let orderState=[];let currentPhoto=null;let paused=false;let currentWager=0;
  const engineMeta={quiz:['🧠','QUIZ'],learn:['🎓','LEARN'],puzzle:['🧩','PUZZLE'],task:['🏆','TASK'],social:['🗳','SOCIAL'],visual:['📸','VISUAL'],music:['🎵','MUSIC']};
  const vibeName=()=>window.PARTYPLAY_CONTENT?.packs?.[session.vibe]?.name||'Custom Mix';
  const competitors=()=>session.competitors||[];
  const activeCompetitor=()=>competitors()[competitorIndex%Math.max(1,competitors().length)];
  const setHidden=(el,hide)=>$(el)?.classList.toggle('hidden',!!hide);
  const saveState=()=>{session.roundIndex=roundIndex;session.competitorIndex=competitorIndex;PP.save(PP.STORAGE.session,session);PP.save(PP.STORAGE.resume,{sessionId:session.id,roundIndex,updatedAt:Date.now()})};
  const sortedCompetitors=()=>[...competitors()].sort((a,b)=>(b.score||0)-(a.score||0));
  function renderScores(){
    const root=$('#scoreList');root.innerHTML='';sortedCompetitors().forEach((c,i)=>{const row=document.createElement('div');row.className='score-row'+(c.id===activeCompetitor()?.id?' active':'');row.innerHTML=`<span class="score-rank">${i+1}</span><span class="score-name">${PP.escapeHTML(c.name)}</span><span class="score-value">${formatScore(c.score||0)}</span>`;root.appendChild(row)});
    $('#packLabel').textContent=vibeName();
  }
  function roundOwner(){if(session.live)return'Everyone plays';const c=activeCompetitor();return c?.name||'Everyone plays'}
  function metaFor(round){const [icon,label]=engineMeta[round.engine]||['🎲','ROUND'];return {icon,label,points:PP.pointsFor(round)}}
  const freshStats=()=>({correct:0,wrong:0,wagered:0,wagerWins:0,puzzleCorrect:0,fastestMs:null});
  function ensureStats(c){if(c&&!c.stats)c.stats=freshStats();return c?.stats}
  function wagerRound(index=roundIndex,round=session.deck[index]){
    const mode=session.wager?.mode||'off';if(mode==='off'||!round||!['quiz','puzzle','visual'].includes(round.engine))return false;
    if(mode==='full')return true;if(mode==='final')return index===session.deck.length-1;
    return index===session.deck.length-1||(index+1)%5===0;
  }
  function wagerOptions(index=roundIndex,round=session.deck[index]){if(!wagerRound(index,round))return[];const max=Math.max(0,Math.min(1,Number(session.wager?.max)||.5));return[0,.25,.5,1].filter(v=>v<=max+1e-9)}
  function sanitizeWager(value){const opts=wagerOptions();const n=Math.max(0,Math.min(1,Number(value)||0));return opts.includes(n)?n:0}
  function formatScore(v){const n=Math.round((Number(v)||0)*100)/100;return Number.isInteger(n)?String(n):n.toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}
  function renderWagerControls(round){
    currentWager=0;const bar=$('#wagerStrip'),root=$('#wagerChoices');if(!bar||!root)return;root.innerHTML='';
    if(session.live||!wagerRound(roundIndex,round)){setHidden('#wagerStrip',true);return}
    setHidden('#wagerStrip',false);$('#wagerPrompt').textContent=`${roundOwner()}: risk part of this round's value?`;
    wagerOptions(roundIndex,round).forEach(pct=>{const b=document.createElement('button');b.type='button';b.className='wager-choice'+(pct===0?' selected':'');b.textContent=pct===0?'No wager':pct===1?'All-in +100%':`Risk ${Math.round(pct*100)}%`;b.addEventListener('click',()=>{currentWager=pct;root.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const base=PP.pointsFor(round),risk=base*pct;$('#wagerNote').textContent=pct?`Correct: +${formatScore(base+risk)} · Wrong: −${formatScore(risk)}. Virtual points only.`:'No extra risk this round.'});root.appendChild(b)});
    $('#wagerNote').textContent='No extra risk this round.';
  }
  function recordResult(c,{correct,wagerPct=0,elapsedMs=0}={}){const st=ensureStats(c);if(!st)return;if(correct){st.correct++;if(currentRound?.engine==='puzzle')st.puzzleCorrect++;if(wagerPct>0)st.wagerWins++;if(elapsedMs>0&&(st.fastestMs==null||elapsedMs<st.fastestMs))st.fastestMs=elapsedMs}else st.wrong++;st.wagered+=Math.max(0,Number(wagerPct)||0)}
  function makeMedia(round){
    const box=$('#roundMedia');box.innerHTML='';box.classList.add('hidden');
    if(round.engine==='visual'&&round.visual){box.classList.remove('hidden');const img=document.createElement('img');img.src=round.visual.image;img.alt=round.visual.alt||'Visual clue';img.referrerPolicy='no-referrer';img.addEventListener('error',()=>{box.innerHTML='<div class="visual-placeholder">🗺️</div>'});box.appendChild(img)}
  }
  function buttonOption(text){const b=document.createElement('button');b.type='button';b.className='option-btn';b.textContent=text;b.addEventListener('click',()=>{localSelection=text;$$('.option-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});return b}
  function renderOrder(root,items){orderState=[...items];const draw=()=>{root.innerHTML='';orderState.forEach((item,i)=>{const row=document.createElement('div');row.className='order-row';row.innerHTML=`<span>${i+1}</span><b>${PP.escapeHTML(item)}</b><button type="button" aria-label="Move up">↑</button><button type="button" aria-label="Move down">↓</button>`;const [up,down]=row.querySelectorAll('button');up.disabled=i===0;down.disabled=i===orderState.length-1;up.addEventListener('click',()=>{if(i>0){[orderState[i-1],orderState[i]]=[orderState[i],orderState[i-1]];draw()}});down.addEventListener('click',()=>{if(i<orderState.length-1){[orderState[i+1],orderState[i]]=[orderState[i],orderState[i+1]];draw()}});root.appendChild(row)})};draw()}
  async function compressPhoto(file){return new Promise((resolve,reject)=>{const img=new Image(),reader=new FileReader();reader.onload=()=>img.src=reader.result;reader.onerror=reject;img.onload=()=>{const max=900,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.72))};reader.readAsDataURL(file)})}
  function renderInteraction(round){
    const root=$('#roundInteraction');root.innerHTML='';localSelection=null;currentPhoto=null;orderState=[];
    if((round.engine==='quiz'||round.engine==='learn')&&round.options?.length){const grid=document.createElement('div');grid.className='option-grid';round.options.forEach(o=>grid.appendChild(buttonOption(o)));root.appendChild(grid);return}
    if(round.engine==='visual'){const wrap=document.createElement('div');wrap.className='typed-answer';wrap.innerHTML='<input id="typedLocal" placeholder="Type your answer or say it aloud…"><button class="btn secondary" type="button">Lock</button>';wrap.querySelector('button').addEventListener('click',()=>{localSelection=wrap.querySelector('input').value.trim();wrap.querySelector('input').disabled=true;wrap.querySelector('button').textContent='Locked ✓'});root.appendChild(wrap);return}
    if(round.engine==='puzzle'){
      if(round.puzzle?.kind==='order'){const div=document.createElement('div');div.className='puzzle-order';renderOrder(div,round.puzzle.items);root.appendChild(div)}else{const wrap=document.createElement('div');wrap.className='typed-answer';wrap.innerHTML=`<input id="typedLocal" placeholder="Your solution…"><button class="btn secondary" type="button">Lock</button>`;wrap.querySelector('button').addEventListener('click',()=>{localSelection=wrap.querySelector('input').value.trim();wrap.querySelector('input').disabled=true;wrap.querySelector('button').textContent='Locked ✓'});root.appendChild(wrap);if(round.puzzle?.hint){const hint=document.createElement('p');hint.className='round-hint';hint.textContent=`Hint: ${round.puzzle.hint}`;root.appendChild(hint)}}return
    }
    if(round.engine==='task'){
      const box=document.createElement('div');box.className='task-box';box.innerHTML=`<strong>${round.task?.proof==='photo'?'📷 Proof photo available':'Host-judged challenge'}</strong><p>Complete the task safely. The host can award points when time is up.</p>`;
      if(round.task?.proof==='photo'&&session.devices?.camera){const photo=document.createElement('div');photo.className='photo-input';photo.innerHTML='<label class="btn secondary">Take / choose photo <input id="proofFile" type="file" accept="image/*" capture="environment" hidden></label>';const input=photo.querySelector('input');input.addEventListener('change',async()=>{if(!input.files?.[0])return;currentPhoto=await compressPhoto(input.files[0]);box.querySelector('.proof-preview')?.remove();const img=document.createElement('img');img.className='proof-preview';img.src=currentPhoto;img.alt='Challenge proof preview';box.appendChild(img);const entry={id:PP.uuid(),roundId:round.id,round:round.prompt,owner:roundOwner(),dataUrl:currentPhoto,createdAt:Date.now()};evidence.push(entry);if(session.live&&liveClient?.connected)liveClient.send('photo-submit',{code:liveRoom,roundId:round.id,dataUrl:currentPhoto})});photo.appendChild(input);box.appendChild(photo)}root.appendChild(box);return
    }
    if(round.engine==='social'){const box=document.createElement('div');box.className='task-box';box.innerHTML='<strong>🗳 Group decision</strong><p>Discuss, vote or point on the host’s count. Use Correct to award the current competitor/team the round points.</p>';root.appendChild(box);return}
    if(round.engine==='music'){
      const box=document.createElement('div');box.className='music-panel';box.innerHTML='<b>Choose how to run this music round</b><span class="round-hint">Use a track you are allowed to play locally, or open a provider search. PartyPlay does not bundle commercial songs.</span><div class="music-providers"></div><label class="btn secondary">Use local audio file <input id="localAudioFile" type="file" accept="audio/*" hidden></label><audio id="localAudio" class="hidden" controls></audio>';
      const p=box.querySelector('.music-providers');[['spotify','Spotify'],['ytmusic','YouTube Music'],['youtube','YouTube'],['audius','Audius']].forEach(([id,label])=>{const a=document.createElement('a');a.target='_blank';a.rel='noopener';a.href=PP.providerUrl(id,round.music?.query||round.answer);a.textContent=label;p.appendChild(a)});const file=box.querySelector('#localAudioFile'),audio=box.querySelector('#localAudio');file.addEventListener('change',()=>{if(file.files?.[0]){audio.src=URL.createObjectURL(file.files[0]);audio.classList.remove('hidden');audio.play().catch(()=>{})}});root.appendChild(box);return
    }
    const wrap=document.createElement('div');wrap.className='typed-answer';wrap.innerHTML='<input id="typedLocal" placeholder="Your answer…"><button class="btn secondary" type="button">Lock</button>';root.appendChild(wrap)
  }
  function renderRound(round){
    currentRound=round;revealed=false;liveResponses=[];$('#responseList').innerHTML='';setHidden('#answerPanel',true);setHidden('#nextButton',true);setHidden('#judgeButton',true);setHidden('#wrongButton',false);setHidden('#correctButton',false);setHidden('#revealButton',false);
    const m=metaFor(round);$('#roundStatus').textContent=`Round ${roundIndex+1} / ${session.deck.length}`;$('#turnKicker').textContent=session.live?'OPEN ROUND':'UP NEXT';$('#turnName').textContent=roundOwner();$('#roundMeta').innerHTML=`<span class="round-engine">${m.icon} ${m.label}</span><span class="difficulty-pill">${String(round.difficulty||'mixed').toUpperCase()} · ${m.points} PTS</span><span class="difficulty-pill">${PP.escapeHTML(round.category||'Mixed')}</span>`;$('#roundPrompt').textContent=round.prompt;$('#roundHint').textContent=round.puzzle?.hint||'';setHidden('#roundHint',!round.puzzle?.hint);$('#pointValue').textContent=`+${m.points}`;makeMedia(round);renderWagerControls(round);renderInteraction(round);renderScores();
    const duration=PP.durationFor(round,session.timerMode);setHidden('#timerWrap',duration<=0);$('#timerText').textContent=duration?`00:${String(duration).padStart(2,'0')}`:'—';
    if(session.live){setHidden('#liveResponsePanel',false);setHidden('#wrongButton',true);setHidden('#correctButton',true);setHidden('#judgeButton',!['task','social','music'].includes(round.engine))}else setHidden('#liveResponsePanel',true);
  }
  function showTransition(){clearTimer();const r=session.deck[roundIndex];const m=metaFor(r);$('#transitionKicker').textContent=`ROUND ${roundIndex+1} OF ${session.deck.length}`;$('#transitionIcon').textContent=m.icon;$('#transitionTitle').textContent=r.category||m.label;$('#transitionSub').textContent=session.live?'Everyone answers on their own device.':`${roundOwner()}, you're up.`;$('#beginRound').textContent='Start round';setHidden('#transitionOverlay',false)}
  function startTimer(){clearTimer();roundStartedAt=Date.now();timeLeft=PP.durationFor(currentRound,session.timerMode);if(!timeLeft){$('#timerText').textContent='—';return}updateTimerUI();timerId=setInterval(()=>{if(paused)return;timeLeft-=1;updateTimerUI();if(timeLeft<=0){clearTimer();revealAnswer(true)}},1000)}
  function updateTimerUI(){const total=Math.max(1,PP.durationFor(currentRound,session.timerMode));$('#timerText').textContent=`00:${String(Math.max(0,timeLeft)).padStart(2,'0')}`;const pct=Math.max(0,timeLeft/total),circ=106.8;$('#timerCircle').style.strokeDashoffset=String(circ*(1-pct));if(session.live&&liveClient?.connected)liveClient.send('timer',{code:liveRoom,timeLeft})}
  function clearTimer(){if(timerId){clearInterval(timerId);timerId=null}}
  function revealAnswer(fromTimer=false){if(revealed)return;revealed=true;clearTimer();$('#answerText').textContent=currentRound.answer||'Host judges the result';$('#answerFact').textContent=currentRound.fact||currentRound.explanation||'';setHidden('#answerPanel',false);setHidden('#revealButton',true);if(session.live){resolveLiveRound();setHidden('#nextButton',false)}else{if(fromTimer)$('#roundHint').textContent='Time! Host, score the result.'}}
  function localCorrect(){const c=activeCompetitor();const pct=sanitizeWager(currentWager),base=PP.pointsFor(currentRound),gain=base+(base*pct);if(c){c.score=(c.score||0)+gain;recordResult(c,{correct:true,wagerPct:pct,elapsedMs:Math.max(0,Date.now()-roundStartedAt)})}finishLocalScoring(true)}
  function localWrong(){const c=activeCompetitor(),pct=sanitizeWager(currentWager),base=PP.pointsFor(currentRound),loss=base*pct;if(c){c.score=Math.max(0,(c.score||0)-loss);recordResult(c,{correct:false,wagerPct:pct,elapsedMs:Math.max(0,Date.now()-roundStartedAt)})}finishLocalScoring(false)}
  function finishLocalScoring(correct){revealAnswer();if(currentRound?.engine==='learn'){const progress=PP.load(PP.STORAGE.progress,{}),key=currentRound.category||'Learning',row=progress[key]||{attempts:0,correct:0};row.attempts+=1;if(correct)row.correct+=1;progress[key]=row;PP.save(PP.STORAGE.progress,progress)}setHidden('#wrongButton',true);setHidden('#correctButton',true);setHidden('#wagerStrip',true);setHidden('#nextButton',false);renderScores();saveState()}
  function nextRound(){clearTimer();if(roundIndex>=session.deck.length-1){finishGame();return}roundIndex++;competitorIndex=(competitorIndex+1)%Math.max(1,competitors().length);saveState();showTransition()}
  function recognitionAwards(){if(session.awards?.recognition===false||!competitors().length)return[];const rows=[];const by=(fn,dir='max')=>[...competitors()].filter(c=>fn(c)!=null).sort((a,b)=>dir==='min'?fn(a)-fn(b):fn(b)-fn(a))[0];const correct=by(c=>ensureStats(c)?.correct||0),risk=by(c=>ensureStats(c)?.wagered||0),fast=by(c=>ensureStats(c)?.fastestMs,'min'),puzzle=by(c=>ensureStats(c)?.puzzleCorrect||0);if(correct&&(correct.stats.correct||0)>0)rows.push(['🎯','Most Correct',correct.name,`${correct.stats.correct} correct`]);if(risk&&(risk.stats.wagered||0)>0)rows.push(['⚡','Biggest Risk Taker',risk.name,`${Math.round(risk.stats.wagered*100)}% total risk`]);if(fast&&fast.stats.fastestMs)rows.push(['⏱','Fastest Answer',fast.name,`${(fast.stats.fastestMs/1000).toFixed(2)}s`]);if(puzzle&&(puzzle.stats.puzzleCorrect||0)>0)rows.push(['🧩','Puzzle Mind',puzzle.name,`${puzzle.stats.puzzleCorrect} solved`]);return rows}
  function finishGame(){clearTimer();session.status='complete';saveState();const sorted=sortedCompetitors(),winner=sorted[0];$('#winnerTitle').textContent=winner?`${winner.name} wins!`:'Game complete!';$('#finalLeaderboard').innerHTML=sorted.map((c,i)=>`<div class="final-row"><span>${i+1}. ${PP.escapeHTML(c.name)}</span><b>${formatScore(c.score||0)}</b></div>`).join('');const prize=session.awards?.winnerPrize?.trim();$('#winnerPrize').textContent=prize?`Winner award: ${prize}`:'';setHidden('#winnerPrize',!prize);const awards=recognitionAwards();$('#recognitionBoard').innerHTML=awards.map(([icon,title,name,detail])=>`<div class="recognition-row"><span>${icon}</span><div><b>${PP.escapeHTML(title)}</b><small>${PP.escapeHTML(name)} · ${PP.escapeHTML(detail)}</small></div></div>`).join('');setHidden('#recognitionBoard',!awards.length);setHidden('#winnerOverlay',false);if(session.live&&liveClient?.connected)liveClient.send('game-finished',{code:liveRoom,scores:sorted,winner:winner?.name||'Winner',prize:prize||'',awards})}
  function rematch(){session.competitors.forEach(c=>{c.score=0;c.stats=freshStats()});roundIndex=0;competitorIndex=0;session.deck=PP.partyDirector(PP.roundsFor(session),session.roundCount||20);session.status='ready';saveState();setHidden('#winnerOverlay',true);showTransition()}
  function openModal(id){setHidden(`#${id}`,false)} function closeModal(id){setHidden(`#${id}`,true)}
  function renderEvidence(){const root=$('#evidenceGrid');root.innerHTML=evidence.length?evidence.map(e=>`<article class="evidence-card"><img src="${e.dataUrl}" alt="Challenge proof"><div><b>${PP.escapeHTML(e.owner)}</b><br>${PP.escapeHTML(e.round)}</div></article>`).join(''):'<p class="round-hint">No proof photos yet.</p>'}
  function renderScoreEditor(){const root=$('#scoreEditor');root.innerHTML='';competitors().forEach(c=>{const row=document.createElement('div');row.className='score-edit-row';row.innerHTML=`<span>${PP.escapeHTML(c.name)}</span><b>${c.score||0}</b><button type="button">−</button><button type="button">+</button>`;const [minus,plus]=row.querySelectorAll('button');minus.addEventListener('click',()=>{c.score=Math.max(0,(c.score||0)-1);row.querySelector('b').textContent=c.score;renderScores();saveState()});plus.addEventListener('click',()=>{c.score=(c.score||0)+1;row.querySelector('b').textContent=c.score;renderScores();saveState()});root.appendChild(row)})}

  // Live host ---------------------------------------------------------------
  function safeRoundForClients(r){const clone=JSON.parse(JSON.stringify(r));delete clone.answer;delete clone.fact;delete clone.explanation;if(clone.puzzle)delete clone.puzzle.correct;return clone}
  function liveLobbyMessage(){const joinUrl=`${location.origin}${location.pathname.replace(/play\.html$/,'join.html')}?room=${encodeURIComponent(liveRoom)}`;$('#transitionKicker').textContent='PARTYPLAY LIVE';$('#transitionIcon').textContent='⚡';$('#transitionTitle').textContent=liveRoom||'Connecting…';$('#transitionSub').innerHTML=liveRoom?`Join with code <b>${PP.escapeHTML(liveRoom)}</b><br><span style="font-size:13px">${PP.escapeHTML(joinUrl)}</span><br><br>${liveParticipants.filter(p=>p.role==='player').length} player device(s) connected.`:'Starting temporary room…';$('#beginRound').textContent=liveRoom?'Start live game':'Connecting…';$('#beginRound').disabled=!liveRoom||liveParticipants.filter(p=>p.role==='player').length<1;setHidden('#transitionOverlay',false)}
  function updateCompetitorsFromLive(){if(session.playStyle==='teams'){const keep=session.teams||[];session.competitors=keep.map(t=>{const existing=competitors().find(c=>c.id===t.id);return{id:t.id,name:t.name,type:'team',members:t.members||[],score:existing?.score||0,stats:existing?.stats||freshStats()}})}else{const old=new Map(competitors().map(c=>[c.id,c]));session.competitors=liveParticipants.filter(p=>p.role==='player').map(p=>{const prior=old.get(p.participantId);return{id:p.participantId,name:p.name,type:'player',score:prior?.score||0,stats:prior?.stats||freshStats()}})}renderScores()}
  function beginLiveRound(){renderRound(session.deck[roundIndex]);setHidden('#transitionOverlay',true);startTimer();liveResponses=[];const duration=PP.durationFor(currentRound,session.timerMode);liveClient.send('round-start',{code:liveRoom,round:safeRoundForClients(currentRound),roundIndex,totalRounds:session.deck.length,duration,startedAt:Date.now(),turn:roundOwner(),scores:competitors(),wagerOptions:wagerOptions(roundIndex,currentRound)})}
  function responseCompetitor(resp){if(session.playStyle==='teams'){const p=liveParticipants.find(x=>x.participantId===resp.participantId);return competitors().find(c=>c.id===(p?.teamId||resp.teamId))}return competitors().find(c=>c.id===resp.participantId)}
  function isCorrectResponse(resp){const r=currentRound;if(!r)return false;if(r.engine==='task'||r.engine==='social'||r.engine==='music')return false;if(r.engine==='puzzle'&&r.puzzle?.kind==='order')return JSON.stringify(resp.answer||[])===JSON.stringify(r.puzzle.correct||[]);const a=PP.normalize(resp.answer);const correct=PP.normalize(r.answer);if(!a)return false;if(a===correct)return true;const aliases=(r.acceptedAnswers||[]).map(PP.normalize);if(aliases.includes(a))return true;return correct.length>4&&(a.includes(correct)||correct.includes(a))}
  function resolveLiveRound(){if(!liveClient?.connected)return;const duration=Math.max(1,PP.durationFor(currentRound,session.timerMode)||20);const seenTeams=new Set();const scored=[];
    liveResponses.sort((a,b)=>(a.receivedAt||0)-(b.receivedAt||0)).forEach(resp=>{const c=responseCompetitor(resp);if(!c)return;if(session.playStyle==='teams'){if(seenTeams.has(c.id))return;seenTeams.add(c.id)}const correct=isCorrectResponse(resp),pct=sanitizeWager(resp.wagerPct);const base=PP.pointsFor(currentRound)*1000,elapsedMs=Math.max(0,Number(resp.serverElapsedMs ?? ((resp.receivedAt||Date.now())-roundStartedAt))),elapsed=elapsedMs/1000;let awarded=0;if(correct){const speed=session.speedScoring?Math.max(0,Math.round(500*(1-Math.min(1,elapsed/duration)))):0;awarded=Math.round(base+(base*pct)+speed);c.score=(c.score||0)+awarded}else if(pct>0){awarded=-Math.round(base*pct);c.score=Math.max(0,(c.score||0)+awarded)}recordResult(c,{correct,wagerPct:pct,elapsedMs});scored.push({...resp,wagerPct:pct,correct,awarded,competitorId:c.id})});
    renderScores();saveState();liveClient.send('round-result',{code:liveRoom,answer:currentRound.answer,fact:currentRound.fact||currentRound.explanation||'',results:scored,scores:competitors(),roundIndex});
  }
  async function initLive(){
    $('#modeStatus').textContent='LIVE';$('#modeStatus').classList.add('live');liveClient=new PartyPlayLiveClient();
    liveClient.on('room-created',msg=>{liveRoom=msg.code;history.replaceState({},'',`play.html?mode=live&room=${encodeURIComponent(liveRoom)}`);liveLobbyMessage()});
    liveClient.on('room-state',msg=>{liveParticipants=msg.participants||[];updateCompetitorsFromLive();liveLobbyMessage()});
    liveClient.on('answer-received',msg=>{liveResponses.push(msg.response);renderLiveResponses()});
    liveClient.on('photo-received',msg=>{if(msg.dataUrl?.startsWith('data:image/')){evidence.push({id:PP.uuid(),roundId:msg.roundId,round:currentRound?.prompt||'Live task',owner:msg.name||'Player',dataUrl:msg.dataUrl,createdAt:Date.now()})}});
    liveClient.on('disconnected',()=>{$('#modeStatus').textContent='LIVE OFFLINE';$('#modeStatus').classList.remove('live')});
    try{await liveClient.connect();liveClient.send('create-room',{session:{playStyle:session.playStyle,teams:session.teams||[],devices:session.devices,vibe:session.vibe}});liveLobbyMessage()}catch(e){setHidden('#transitionOverlay',false);$('#transitionKicker').textContent='LIVE SERVER NOT RUNNING';$('#transitionIcon').textContent='🔌';$('#transitionTitle').textContent='Local play is still ready.';$('#transitionSub').innerHTML='PartyPlay Live needs the included realtime server. Run <b>npm start</b>, or deploy the included Node server. No database is used.';$('#beginRound').textContent='Continue locally';$('#beginRound').disabled=false;$('#beginRound').onclick=()=>{session.live=false;$('#modeStatus').textContent='LOCAL';showTransition()}}
  }
  function renderLiveResponses(){const count=liveParticipants.filter(p=>p.role==='player').length;$('#responseCount').textContent=`${liveResponses.length} / ${count}`;$('#responseList').innerHTML=liveResponses.map(r=>`<div class="response-chip"><b>${PP.escapeHTML(r.name||'Player')}</b><br>${Math.max(0,((r.receivedAt||Date.now())-roundStartedAt)/1000).toFixed(2)}s</div>`).join('')}

  // Controls ----------------------------------------------------------------
  $('#beginRound').addEventListener('click',()=>{if(session.live){if(!liveRoom)return;beginLiveRound()}else{renderRound(session.deck[roundIndex]);setHidden('#transitionOverlay',true);startTimer()}});
  $('#revealButton').addEventListener('click',()=>revealAnswer(false));$('#correctButton').addEventListener('click',localCorrect);$('#wrongButton').addEventListener('click',localWrong);$('#judgeButton').addEventListener('click',()=>{renderScoreEditor();openModal('scoreModal')});$('#nextButton').addEventListener('click',nextRound);
  $('#pauseButton').addEventListener('click',()=>{paused=true;setHidden('#pauseOverlay',false)});$('#resumeButton').addEventListener('click',()=>{paused=false;setHidden('#pauseOverlay',true)});
  $('#menuButton').addEventListener('click',()=>setHidden('#gameMenu',false));$('#closeMenu').addEventListener('click',()=>setHidden('#gameMenu',true));
  $('#skipRound').addEventListener('click',()=>{setHidden('#gameMenu',true);nextRound()});$('#adjustScore').addEventListener('click',()=>{renderScoreEditor();openModal('scoreModal');setHidden('#gameMenu',true)});$('#openEvidence').addEventListener('click',()=>{renderEvidence();openModal('evidenceModal');setHidden('#gameMenu',true)});$('#changeDevices').addEventListener('click',()=>{PP.save(PP.STORAGE.session,session);location.href='setup.html?mode=party'});
  $$('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.closeModal)));$('#clearEvidence').addEventListener('click',()=>{evidence=[];renderEvidence()});$('#rematchButton').addEventListener('click',rematch);$('#recapButton').addEventListener('click',()=>{const sorted=sortedCompetitors(),prize=session.awards?.winnerPrize?.trim();alert(`PartyPlay recap\n\nWinner: ${sorted[0]?.name||'—'}\nScore: ${formatScore(sorted[0]?.score||0)}${prize?`\nWinner award: ${prize}`:''}\nRounds played: ${session.deck.length}\nPhotos captured: ${evidence.length}\nWager mode: ${session.wager?.mode||'off'}\n\nRecap stays on this device.`)});
  $('#collapseScores').addEventListener('click',()=>document.body.classList.toggle('scores-collapsed'));
  $('#tvButton').addEventListener('click',async()=>{if(session.live&&liveRoom){window.open(`display.html?room=${encodeURIComponent(liveRoom)}`,'partyplay-display');return}document.body.classList.toggle('tv-local');try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}});
  document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.code==='Space'){e.preventDefault();revealAnswer(false)}if(e.key==='ArrowRight'&&revealed)nextRound()});

  renderScores();$('#packLabel').textContent=vibeName();
  if(session.live)initLive();else showTransition();
})();
